# Generated by Django 3.2.4 on 2021-06-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210618_1324'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='tb_article',
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table='tb_category',
        ),
    ]
